project:
  type: website

website:
  title: "Let's Do Digital"
  navbar:
    home: "https://letsdodigital.org/"
    left:
      - href: index.qmd
        text: Home
  favicon: media/ldd-logo.png

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true



