project:
  type: website

website:
  title: "CWC"
  navbar:
    left:
      - href: index.qmd
        text: Home
  favicon: media/cwc-logo.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



