project:
  type: website

website:
  title: "LDD"
  navbar:
    left:
      - href: index.qmd
        text: Home
  favicon: media/ldd-logo.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



